export type BottomCard = {
  image: string;
  alt: string;
  text: string;
  date: string;
  location: string;
  mode: string;
  teamSize: string;
  deadline: string;
  description: string;
};

export type ModuleData = {
  title: string;
  btntitle: string;
  heroRows: string[][];
  description: string[];
  bottomCards: BottomCard[];
  galleryImages: string[];
};

export const eventModules: Record<string, ModuleData> = {
  empresario: {
    title: "EMPRESARIO",
    btntitle: "EMPRESARIO",
    heroRows: [
      [
        "/images/empresario/image1.jpg",
        "/images/empresario/image2.jpg",
        "/images/empresario/image3.jpg",
        "/images/empresario/image4.jpg",
        "/images/empresario/image5.webp",
        "/images/empresario/image6.webp",
      ],
      [
        "/images/empresario/image7.webp",
        "/images/empresario/image8.webp",
        "/images/empresario/image9.webp",
        "/images/empresario/image10.webp",
        "/images/empresario/image11.png",
        "/images/empresario/image12.png",
      ],
      [
        "/images/empresario/image13.png",
        "/images/empresario/image14.png",
        "/images/empresario/image15.png",
        "/images/empresario/image16.png",
        "/images/empresario/image17.png",
        "/images/empresario/image18.png",
      ],
    ],
    description: [
      `<b class="text-[var(--blue-accent)]">EMPRESARIO</b>, the flagship entrepreneurial challenge of<b class="text-[var(--blue-accent)]"> E-CELL NIT SILCHAR</b> is back, a space where ideas begin as individual points and gradually connect, like elements on a grid, forming something greater than the sum of their parts. It's not just a competition; it's a environment for thinkers, builders, and dreamers who believe every idea has a place, it just needs the right alignment.`,
      `Here, every pitch is a piece of the puzzle.</br>Every challenge shifts your perspective.</br> Every conversation draws a new line on your canvas.`,

      `Pitch. Compete. Collaborate.</br> Find your pattern. Build your framework.</br> And grow into the entrepreneur you aspire to be.`,

      `<b class="text-[var(--blue-accent)]">16th - 18th January.</b></br> Unleash your entrepreneurial spirit.`,
    ],
    bottomCards: [
      {
        image: "/images/empresario/business_hackathon.png",
        alt: "Business Hackathon",
        text: "Business Hackathon",
        date: "January 17th, 2026",
        location: "Start-Up Centre",
        mode: "On-site",
        teamSize: "3-5 members",
        deadline: "January 5th, 2026",
        description:
          "Enter the digital dimension where creativity is your code and strategy is your weapon. In this realm of visionaries, strategists, and innovators, ideas transcend boundaries and solutions reshape realities. Two rounds await: online submission and onsite hackathon.",
      },
      {
        image: "/images/empresario/Treasure_hunt.jpeg",
        alt: "Treasure Hunt",
        text: "Treasure Hunt",
        date: "January 18th, 2026",
        location: "NIT Silchar Campus Wide",
        mode: "On-site",
        teamSize: "3-5 members",
        deadline: "January 12th, 2026",
        description:
          "Get ready for the ultimate campus adventure! Navigate through clues and riddles in this high-stakes treasure hunt where every step tests your wit and every discovery brings you closer to victory. Three thrilling rounds await the brave.",
      },
      {
        image: "/images/empresario/bid-wise.jpeg",
        alt: "Bid-Wise",
        text: "Bid-Wise",
        date: "January 17th, 2026",
        location: "New Gallery",
        mode: "On-site",
        teamSize: "3-5 members",
        deadline: "January 12th, 2026",
        description:
          "Welcome to The Silent Grid: a high-stakes auction where words fall silent and only your moves speak. Manage a 100-point purse and limited bidding tokens across 6 rounds of exploration, discussion, and secret bidding at 10 stalls. Use the Special Token wisely—some rounds may eliminate it. Top 10 teams advance.",
      },
      {
        image: "/images/empresario/Adovation.png",
        alt: "Adovation",
        text: "Adovation",
        date: "January 18th, 2026",
        location: "Online Submission",
        mode: "Online",
        teamSize: "3-6 members",
        deadline: "January 12th, 2026",
        description:
          "A Tecnoesis 'Empressario' Module Event by Ecell. Teams will create engaging promotional videos for assigned shops, showcasing their marketing creativity and video production skills.",
      },
      {
        image: "/images/empresario/startupexpo.png",
        alt: "Start-Up Expo",
        text: "Start-Up Expo",
        date: "January 16th, 2026",
        location: "New Gallery",
        mode: "On-site",
        teamSize: "Minimum 1 member",
        deadline: "January 5th, 2026",
        description:
          "Transform your innovative ideas into reality at the ultimate startup showcase! Present your business concepts, connect with investors, and compete for funding opportunities. Two dynamic rounds: application submission and live exhibition.",
      },
    ],
    galleryImages: [
      "/images/empresario/image1.jpg",
      "/images/empresario/image2.jpg",
      "/images/empresario/image3.jpg",
      "/images/empresario/image4.jpg",
      "/images/empresario/image5.webp",
      "/images/empresario/image6.webp",
      "/images/empresario/image7.webp",
      "/images/empresario/image8.webp",
      "/images/empresario/image9.webp",
      "/images/empresario/image10.webp",
      "/images/empresario/image11.png",
      "/images/empresario/image12.png",
      "/images/empresario/image13.png",
      "/images/empresario/image14.png",
      "/images/empresario/image15.png",
      "/images/empresario/image16.png",
      "/images/empresario/image17.png",
      "/images/empresario/image18.png",
    ],
  },
  orientation: {
    title: "EnGenius",
    btntitle: "EnGenius",
    heroRows: [
      [
        "/images/orientation/orientation1.png",
        "/images/orientation/orientation2.png",
        "/images/orientation/orientation3.png",
        "/images/orientation/orientation4.png",
        "/images/orientation/orientation5.png",
        "/images/orientation/orientation6.png",
        "/images/orientation/orientation7.png",
        "/images/orientation/orientation8.png",
        "/images/orientation/orientation9.png",
      ],
      [
        "/images/orientation/orientation10.png",
        "/images/orientation/orientation11.png",
        "/images/orientation/orientation12.png",
        "/images/orientation/orientation13.png",
        "/images/orientation/orientation14.png",
        "/images/orientation/orientation15.png",
        "/images/orientation/orientation16.png",
        "/images/orientation/orientation17.png",
        "/images/orientation/orientation18.png",
      ],
      [
        "/images/orientation/orientation19.png",
        "/images/orientation/orientation20.png",
        "/images/orientation/orientation21.png",
        "/images/orientation/orientation22.png",
        "/images/orientation/orientation23.png",
        "/images/orientation/orientation24.png",
        "/images/orientation/orientation25.png",
        "/images/orientation/orientation26.png",
        "/images/orientation/orientation27.png",
      ],
    ],
    description: [
      `Step into the gateway of innovation with <b class="text-[var(--blue-accent)]">EnGenius</b>, the flagship orientation module of <b class="text-[var(--blue-accent)]">E-CELL NIT SILCHAR</b>. It is more than just an introduction; it is the spark that transforms curious minds into visionary creators. Here, we lay the foundation of the entrepreneurial mindset—where students transition from being passive learners to active problem solvers.`,
      `It is an interactive and fun event organized exclusively for the 1st year batch to give them a taste of how entrepreneurship works.`,
      `Orientation introduces new students to entrepreneurship, networking, and E-Cell activities.`,
    ],
    bottomCards: [
      {
        image: "/images/orientation/orientation.jpeg",
        alt: "Orientation",
        text: "EnGenius",
        date: "September 8th, 2025",
        location: "New Gallery",
        mode: "on-site",
        teamSize: "",
        deadline: "",
        description:
          "An interactive and fun event organized exclusively for the 1st year batch to give them a taste of how entrepreneurship works.",
      },
      {
        image: "/images/orientation/pitchboxing.jpeg",
        alt: "Pitchboxing",
        text: "Pitch-boxing",
        date: "September 6th, 2025",
        location: "Start-Up Centre",
        mode: "on-site",
        teamSize: "1 member",
        deadline: "",
        description:
          "Introducing Pitchboxing - the ultimate roast battle where participants will take friendly digs at each other's brand with some sick burns and leave the crowd awestruck.",
      },
      {
        image: "/images/orientation/bechkedikhao.jpeg",
        alt: "Bech ke Dikhao",
        text: "Bech ke Dikhao",
        date: "September 8th, 2025",
        location: "New Gallery",
        mode: "on-site",
        teamSize: "2-5 members",
        deadline: "",
        description:
          "Now, it's your chance to showcase your creativity and persuasive prowess. In Bech Ke Dikhao humour, creativity, and courage are your best allies as you pitch your mystery product. Do you have what it takes to be the ultimate salesperson? Put your skills to the test in this thrilling event.",
      },
      {
        image: "/images/orientation/brandresurrection.jpeg",
        alt: "Brand Resurrection",
        text: "Brand Resurrection",
        date: "September 7th, 2025",
        location: "Online Submission",
        mode: "online",
        teamSize: "1 member",
        deadline: "",
        description:
          "Some brands once ruled their time, only to fade into silence. Now, it’s your chance to bring them back with vision, power, and creativity. This is Brand Resurrection, where forgotten names rise again, reimagined for a new era. A transformation as timeless as moving from Vito to Michael, evolution, revival, and legacy reborn.",
      },
      {
        image: "/images/orientation/sharktank.jpeg",
        alt: "Shark Tank",
        text: "Shark Tank",
        date: "September 7th, 2025",
        location: "Start-Up Centre",
        mode: "on-site",
        teamSize: "2-5 members",
        deadline: "",
        description:
          "In the enchanting realm of Shark Tank, we promise an evening filled with electrifying excitement. Imagine stepping onto a brilliantly lit red carpet, making your grand entrance through an awe-inspiring shark-jaw arch, setting the stage for an event that redefines what's possible.",
      },
    ],
    galleryImages: [
      "/images/orientation/orientation1.png",
      "/images/orientation/orientation2.png",
      "/images/orientation/orientation3.png",
      "/images/orientation/orientation4.png",
      "/images/orientation/orientation5.png",
      "/images/orientation/orientation6.png",
      "/images/orientation/orientation7.png",
      "/images/orientation/orientation8.png",
      "/images/orientation/orientation9.png",
      "/images/orientation/orientation10.png",
      "/images/orientation/orientation11.png",
      "/images/orientation/orientation12.png",
      "/images/orientation/orientation13.png",
      "/images/orientation/orientation14.png",
      "/images/orientation/orientation15.png",
      "/images/orientation/orientation16.png",
      "/images/orientation/orientation17.png",
      "/images/orientation/orientation18.png",
      "/images/orientation/orientation19.png",
      "/images/orientation/orientation20.png",
      "/images/orientation/orientation21.png",
      "/images/orientation/orientation22.png",
      "/images/orientation/orientation23.png",
      "/images/orientation/orientation24.png",
      "/images/orientation/orientation25.png",
      "/images/orientation/orientation26.png",
      "/images/orientation/orientation27.png",
    ],
  },
  srijan: {
    title: "SRIJAN",
    btntitle: "SRIJAN",
    heroRows: [
      [
        "/images/srijan/srijan1.png",
        "/images/srijan/srijan2.png",
        "/images/srijan/srijan3.png",
        "/images/srijan/srijan4.png",
        "/images/srijan/srijan5.png",
        "/images/srijan/srijan6.png",
        "/images/srijan/srijan7.png",
        "/images/srijan/srijan8.png",
      ],
      [
        "/images/srijan/srijan9.png",
        "/images/srijan/srijan10.png",
        "/images/srijan/srijan11.png",
        "/images/srijan/srijan12.png",
        "/images/srijan/srijan13.png",
        "/images/srijan/srijan14.png",
        "/images/srijan/srijan15.png",
        "/images/srijan/srijan16.png",
      ],
      [
        "/images/srijan/srijan17.png",
        "/images/srijan/srijan18.png",
        "/images/srijan/srijan19.png",
        "/images/srijan/srijan20.png",
        "/images/srijan/srijan21.png",
        "/images/srijan/srijan22.png",
        "/images/srijan/srijan23.png",
        "/images/srijan/srijan24.png",
        "/images/srijan/srijan25.png",
      ],
    ],
    description: [
      `The National Innovation and Entrepreneurship Summit of NIT Silchar, <b class="text-[var(--blue-accent)]">Srijan </b>is the flagship event of the<b class="text-[var(--blue-accent)]"> E-CELL, NIT SILCHAR </b>, which is an initiative to motivate and educate people about entrepreneurship as well as have a community-based learning experience with people from varied domains. Numerous events and webinars are held whose main motive is to give shape to the innovative ideas put forward by all the creative minds. It tries to inculcate the spirit of entrepreneurship in the young minds.`,
    ],
    bottomCards: [
      {
        image: "/images/srijan/stockmarketsimulation.webp",
        alt: "Stock Market Simulation",
        text: "Stock Market Simulation",
        date: "April 11th-13th, 2022",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "This event was organised for the stock market enthusiasts public, who could invest and check their knowledge of the stock market, while also competing with the other participants for the cash prize.",
      },
      {
        image: "/images/srijan/casestudycanvas.webp",
        alt: "Case Study Canvas",
        text: "Case Study Canvas",
        date: "April 11th, 2022",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "The downfall of a particular brand was thoroughly studied and researched, in this event. The participants learnt about what not to do during their entrepreneurship journey",
      },
      {
        image: "/images/srijan/entrepreneurshipauction.webp",
        alt: "Entrepreneurship Auction",
        text: "Entrepreneurship Auction",
        date: "April 11th, 2022",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "This event gave a wonderful platform for startup founders to develop entrepreneurial sagacity while also paving the route to structure their goal by bidding for essentials against the firm stock.",
      },
      {
        image: "/images/srijan/startupexpo.webp",
        alt: "Start-Up Expo",
        text: "Start-Up Expo",
        date: "April 11th, 2022",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "This event was a high-visibility platform where emerging entrepreneurs could showcase their ideas and ventures, and attract partnerships, guidance and opportunities.",
      },
      {
        image: "/images/srijan/exchangeyourideas.webp",
        alt: "Exchange Your Ideas",
        text: "Exchange Your Ideas",
        date: "April 10th, 2022",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "Taking the line the ideas of one can be a challenge for others as their motto, this event brought all the competitors together by giving them a space to exchange ideas with each other and still get the winning spot.",
      },
      {
        image: "/images/srijan/outwittheboardroom.webp",
        alt: "Outwit The Boardroom",
        text: "Outwit The Boardroom",
        date: "",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "In this event, the team members of each team were given the role of the managing body of a company, and their managerial skills were put to test.",
      },
      {
        image: "/images/srijan/technerds.webp",
        alt: "Tech Nerds",
        text: "Tech Nerds",
        date: "",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "Organised in collaboration with the Google Developers Student Club, Tech-nerds provided a stage for the participants to come up with a technical solution to a real-life problem.",
      },
      {
        image: "/images/srijan/pitchplz.webp",
        alt: "Pitch Please",
        text: "Pitch Please",
        date: "",
        location: "",
        mode: "",
        teamSize: "",
        deadline: "",
        description:
          "This event provided the participants with a pitching ground where they could come forth and prove their merit to a panel of judges, and showcase that they were pitch-perfect.",
      },
    ],
    galleryImages: [
      "/images/srijan/srijan1.png",
      "/images/srijan/srijan2.png",
      "/images/srijan/srijan3.png",
      "/images/srijan/srijan4.png",
      "/images/srijan/srijan5.png",
      "/images/srijan/srijan6.png",
      "/images/srijan/srijan7.png",
      "/images/srijan/srijan8.png",
      "/images/srijan/srijan9.png",
      "/images/srijan/srijan10.png",
      "/images/srijan/srijan11.png",
      "/images/srijan/srijan12.png",
      "/images/srijan/srijan13.png",
      "/images/srijan/srijan14.png",
      "/images/srijan/srijan15.png",
      "/images/srijan/srijan16.png",
      "/images/srijan/srijan17.png",
      "/images/srijan/srijan18.png",
      "/images/srijan/srijan19.png",
      "/images/srijan/srijan20.png",
      "/images/srijan/srijan21.png",
      "/images/srijan/srijan22.png",
      "/images/srijan/srijan23.png",
      "/images/srijan/srijan24.png",
      "/images/srijan/srijan25.png",
    ],
  },
  eic: {
    title: "ENTREPRENEURSHIP & INNOVATION CHALLENGE",
    btntitle: "EIC",
    heroRows: [
      [
        "/images/eic/eic1.png",
        "/images/eic/eic2.png",
        "/images/eic/eic3.png",
        "/images/eic/eic4.png",
        "/images/eic/eic5.png",
        "/images/eic/eic6.png",
        "/images/eic/eic7.png",
      ],
      [
        "/images/eic/eic8.png",
        "/images/eic/eic9.png",
        "/images/eic/eic10.png",
        "/images/eic/eic11.png",
        "/images/eic/eic12.png",
        "/images/eic/eic13.png",
        "/images/eic/eic14.png",
      ],
      [
        "/images/eic/eic15.png",
        "/images/eic/eic16.png",
        "/images/eic/eic17.png",
        "/images/eic/eic18.png",
        "/images/eic/eic19.png",
        "/images/eic/eic20.png",
        "/images/eic/eic21.png",
      ],
    ],
    description: [
      `The <b class="text-[var(--blue-accent)]">Entrepreneurship and Innovation Challenge (EIC)</b> is a event that bring all the six branches of <b>NIT SILCHAR </b>against each other has five very successful modules under it. All five events have a wide range of participants coming in from each branch.`,
      `<b>EIC Events</b>-</br>
1) Board of Directors - Group Discussion</br>
2) Business Beats - Quiz</br>
3) Campus Rewired - Pitching Round</br>
4) The Entrepreneur's Escape - Breaking the Loop</br>
5) Ad-o-venture - Advertisement Video`,
      `Entrepreneurship cannot be simply confined to making an idea successful; it involves constant hard work, passion and perseverance. Its a process involving a person or a group of people coming up with innovative ideas, researching, conducting surveys, studying the market, and leaving no stone unturned in converting his dream into a Million-Dollar Reality by starting from scratch.`,
    ],
    bottomCards: [
      {
        image: "/images/eic/boardofdirectors.jpeg",
        alt: "Board of Directors",
        text: "Board of Directors",
        date: "January 26th, 2025",
        location: "Start-Up Centre",
        mode: "on-site",
        teamSize: "",
        deadline: "",
        description:
          "Step into the Board of Directors and become Spotify’s trailblazers, where group discussions transform into a symphony of ideas and innovation. Unite, debate, and fine-tune your ideas into a symphony of innovation. Collaborate, debate, and refine your vision to hit all the right notes. Will your collective brilliance set the tone for triumph or fade into obscurity? The stage is yours!",
      },
      {
        image: "/images/eic/adoventure.jpeg",
        alt: "Ad-O-Venture",
        text: "Ad-O-Venture",
        date: "January 27th, 2025",
        location: "Online Submission",
        mode: "online",
        teamSize: "",
        deadline: "",
        description:
          "Welcome to Ad-o-venture, where creativity meets the rhythm of Spotify! Your challenge is to create compelling advertisement that’s concise, engaging, and memorable—all in just 45-60 seconds. Think of it like crafting the perfect playlist: every word needs to hit the right note. Be professional, keep it entertaining, and leave your audience with a tagline they won’t forget. Now it’s your turn to shine—will your ad become the hit of the event or just another skipped track? The stage is yours!",
      },
      {
        image: "/images/eic/businessbeats.jpeg",
        alt: "Business Beats",
        text: "Business Beats",
        date: "January 26th, 2025",
        location: "New Gallery",
        mode: "on-site",
        teamSize: "",
        deadline: "",
        description:
          "Gear up for “Business Beats” the ultimate quiz competition organized by E-Cell in collaboration with NITS Quiz Club, under the EIC module. Get ready to navigate through a Spotify playlist of exciting challenges where each question tests your business acumen and strategic thinking. It’s your time to shine, so tune in, stay sharp, and prove you’ve got what it takes to rise to the top.",
      },
      {
        image: "/images/eic/campusrewired.jpeg",
        alt: "Campus Rewired",
        text: "Campus Rewired",
        date: "January 27th, 2025",
        location: "Start-Up Centre",
        mode: "on-site",
        teamSize: "",
        deadline: "",
        description:
          "Entrepreneurship and Innovation Challenge (EIC) 2025 brings to you ‘Campus Rewired’, a pitching event with a rhythmic engineering spin to it. Is there a problem on campus that’s been bugging you? Much like how Spotify curates the perfect playlist for every mood of yours, you now have the opportunity to fix the problem, but there’s a twist. The solution must include an element that represents your branch. Compose your solution using a presentation and pitch it in front of our judges to see if your branch could be at the top of the list. Set your playlist to work mode, and showcase your innovation and entrepreneurial spirit!!",
      },
      {
        image: "/images/eic/entrepreneurescape.jpeg",
        alt: "Entrepreneur Escape",
        text: "The Entrepreneur's Escape",
        date: "January 28th, 2025",
        location: "Start-Up Centre",
        mode: "on-site",
        teamSize: "",
        deadline: "",
        description:
          "“Breaking the Loop-Escape the Startup” is an exciting challenge where teamwork and quick thinking are your best assets! Like creating the perfect playlist on Spotify, you and your team will piece together clues to unlock the final mystery. Every puzzle solved brings you closer to the grand escape, and just like finding the perfect rhythm in a song, the right strategy will be key to success. Can your team hit all the right notes before time runs out?",
      },
    ],
    galleryImages: [
      "/images/eic/eic1.png",
      "/images/eic/eic2.png",
      "/images/eic/eic3.png",
      "/images/eic/eic4.png",
      "/images/eic/eic5.png",
      "/images/eic/eic6.png",
      "/images/eic/eic7.png",
      "/images/eic/eic8.png",
      "/images/eic/eic9.png",
      "/images/eic/eic10.png",
      "/images/eic/eic11.png",
      "/images/eic/eic12.png",
      "/images/eic/eic13.png",
      "/images/eic/eic14.png",
      "/images/eic/eic15.png",
      "/images/eic/eic16.png",
      "/images/eic/eic17.png",
      "/images/eic/eic18.png",
      "/images/eic/eic19.png",
      "/images/eic/eic20.png",
      "/images/eic/eic21.png",
    ],
  },
  eminence: {
    title: "Eminence",
    btntitle: "Eminence",
    heroRows: [
      [
        "/images/eminence/eminence1.png",
        "/images/eminence/eminence2.png",
        "/images/eminence/eminence3.png",
      ],
      [
        "/images/eminence/eminence4.png",
        "/images/eminence/eminence5.png",
        "/images/eminence/eminence6.png",
      ],
      [
        "/images/eminence/eminence7.png",
        "/images/eminence/eminence8.png",
        "/images/eminence/eminence9.png",
      ],
    ],
    description: [
      `<b class="text-[var(--blue-accent)]">Eminence</b>, known as the Bermuda Triangle of Entrepreneurship, is <b class="text-[var(--blue-accent)]">E-CELL NIT Silchar’s</b> most intellectually stimulating and thought-provoking event. Designed to challenge conventional thinking, it pushes participants to step beyond comfort zones and confront real-world entrepreneurial uncertainties.`,
      `Through case studies, brainstorming exercises, and unconventional business challenges, participants enter with raw ideas and unanswered questions, only to emerge with sharper strategies, clearer perspectives, and stronger decision-making skills. Eminence is not about providing ready solutions; it’s about reshaping mindsets, testing resilience, and encouraging bold, innovative thinking.`,
      `By navigating the unknown waters of entrepreneurship, participants leave more confident, adaptable, and prepared to turn challenges into opportunities—making Eminence a true transformation experience.`,
    ],
    bottomCards: [
      {
        image: "/images/eminence/eminence.jpeg",
        alt: "Eminence",
        text: "E-QUESTA (ROUND 1)",
        date: "April 11th, 2025",
        location: "New Gallery",
        mode: "on-site",
        teamSize: "1 member",
        deadline: "",
        description:
          "The gateway to EMINENCE, this fast-paced challenge will test your entrepreneurial aptitude and problem-solving skills. Only the sharpest, most analytical minds will break through. But that’s not all—those who don’t qualify might just find an unexpected way back into the competition through a wildcard twist.",
      },
      {
        image: "/images/eminence/eminence.jpeg",
        alt: "Eminence",
        text: "E-HACK (ROUND 2)",
        date: "April 12th, 2025",
        location: "Start-Up Centre",
        mode: "on-site",
        teamSize: "",
        deadline: "",
        description:
          "A dynamic business hackathon awaits the qualifiers of E-Questa. In assigned teams, they’ll be given a problem statement to brainstorm, to which they craft innovative, scalable solutions.",
      },
      {
        image: "/images/eminence/eminence.jpeg",
        alt: "Eminence",
        text: "FOUNDERS X FUNDERS (ROUND 3)",
        date: "April 13th, 2025",
        location: "New Gallery",
        mode: "on-site",
        teamSize: "",
        deadline: "",
        description:
          "The arena where top teams pitch, negotiate, and turn ideas into ventures. Startups must impress investors, who analyze and bet on potential. But here’s the twist—investors are judged too. Success hinges on both sharp pitches and strategic bets.",
      },
    ],
    galleryImages: [
      "/images/eminence/eminence1.png",
      "/images/eminence/eminence2.png",
      "/images/eminence/eminence3.png",
      "/images/eminence/eminence4.png",
      "/images/eminence/eminence5.png",
      "/images/eminence/eminence6.png",
      "/images/eminence/eminence7.png",
      "/images/eminence/eminence8.png",
      "/images/eminence/eminence9.png",
    ],
  },
};
